import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Naviagation";
import Script from "next/script";
import { Analytics } from "@vercel/analytics/next"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
      dir="rtl"
    >
      <header>
        {/* <Script src="https://pl30246646.effectivecpmnetwork.com/58/ea/6f/58ea6f4451908c3bf28ca3bc074877a4.js" /> */}

      </header>
      <Analytics />
      <Navbar />
      <body className="min-h-full text-gray-900 selection:bg-blue-500 selection:text-white">
        <div dir="rtl" className="min-h-screen text-gray-800 p-4 md:p-8 font-sans max-w-4xl mx-auto">
          {children}
          </div>
          </body>
    </html>
  );
}
