import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Naviagation";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
    >
      <header>
        {/* <Script src="https://pl30246646.effectivecpmnetwork.com/58/ea/6f/58ea6f4451908c3bf28ca3bc074877a4.js" /> */}

      </header>
      <Navbar />
      <body className="min-h-full flex flex-col container mx-auto max-w-screen-2xl  text-gray-900 selection:bg-blue-500 selection:text-white">{children}</body>
    </html>
  );
}
